apiVersion: v1
kind: Service
metadata:
 name: dapp-ui-service
 namespace: dapp-ui
 labels:
   app: dapp-ui
spec:
 type: NodePort
 selector:
   app: dapp-ui
 ports:
 - protocol: TCP
   port: 80
   targetPort: 80
   name: http

--- 
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: dapp-ui-certificate
  namespace: dapp-ui
spec:
  domains:
  - dapp.propchain.io

--- 
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: dapp-ui-frontend-config
  namespace: dapp-ui
spec:
  redirectToHttps:
    enabled: true
